server {
    listen 8080;
    server_name _;

    location = /ui/console-theme/mass-console.css {
        default_type text/css;
        alias /etc/nginx/console-theme/mass-console.css;
    }

    location = /ui/console-theme/mass-console.js {
        default_type application/javascript;
        alias /etc/nginx/console-theme/mass-console.js;
    }

    location = /ui/login-theme/mass-login.css {
        default_type text/css;
        alias /etc/nginx/console-theme/mass-login.css;
    }

    location = /ui/login-theme/mass-login.js {
        default_type application/javascript;
        alias /etc/nginx/console-theme/mass-login.js;
    }

    location = /ui/login-theme/massdata-logo.png {
        default_type image/png;
        alias /etc/nginx/console-theme/massdata-logo.png;
    }

    location = / {
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Accept-Encoding "";

        sub_filter_once on;
        sub_filter '</head>' '<link rel="stylesheet" href="/ui/login-theme/mass-login.css?v=20260510m"><script src="/ui/login-theme/mass-login.js?v=20260510g"></script></head>';

        proxy_pass http://zitadel-login:3000/ui/v2/login/;
    }

    location /ui/v2/login {
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Accept-Encoding "";

        sub_filter_once on;
        sub_filter '</head>' '<link rel="stylesheet" href="/ui/login-theme/mass-login.css?v=20260510m"><script src="/ui/login-theme/mass-login.js?v=20260510g"></script></head>';

        proxy_pass http://zitadel-login:3000;
    }

    location / {
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Accept-Encoding "";

        sub_filter_once on;
        sub_filter '</head>' '<link rel="stylesheet" href="/ui/console-theme/mass-console.css?v=20260510j"><script src="/ui/console-theme/mass-console.js?v=20260510c"></script></head>';

        proxy_pass http://zitadel-api:8080;
    }
}
